export type PdfTemplateSchemaPackageName = '@asym/pdf-template-schema';
export type PdfTemplateSchemaMaturity = 'phase-22-calculation-engine';
export type PdfTemplateSchemaRuntime = 'shared';
export type PdfTemplateSchemaOwnership = 'template-schema';

export interface PdfTemplateSchemaBoundary {
  readonly packageName: PdfTemplateSchemaPackageName;
  readonly maturity: PdfTemplateSchemaMaturity;
  readonly owns: PdfTemplateSchemaOwnership;
  readonly runtime: PdfTemplateSchemaRuntime;
}

export const pdfTemplateSchemaBoundary: PdfTemplateSchemaBoundary = {
  packageName: '@asym/pdf-template-schema',
  maturity: 'phase-22-calculation-engine',
  owns: 'template-schema',
  runtime: 'shared',
};

export {
  ConditionalOperatorSchema,
  type ConditionalRule,
  ConditionalRuleSchema,
  type DataBinding,
  DataBindingSchema,
  type RepeaterBinding,
  type RepeaterBindingInput,
  RepeaterBindingSchema,
  type TableBinding,
  type TableBindingInput,
  TableBindingSchema,
  type TableColumnBinding,
  TableColumnBindingSchema,
  type TableGroupingBinding,
  TableGroupingBindingSchema,
  type TableTotalBinding,
  TableTotalBindingSchema,
} from './bindings';
export {
  type CalculatedTableGroupTotal,
  type CalculatedTableTotal,
  type CalculateFinancialTotalsInput,
  type CalculateFinancialTotalsResult,
  type CalculateGroupedTableTotalsInput,
  type CalculateGroupedTableTotalsResult,
  type CalculateInvoiceTotalsInput,
  type CalculateInvoiceTotalsResult,
  type CalculateNumericAggregateInput,
  type CalculateNumericAggregateResult,
  type CalculateTableTotalsInput,
  type CalculateTableTotalsResult,
  type CalculateTaxDeductibleAmountInput,
  type CalculateTaxDeductibleAmountResult,
  type CalculationDecimalValue,
  type CalculationDiagnostic,
  type CalculationDiagnosticCode,
  type CalculationDiagnosticSeverity,
  type CalculationOperation,
  type CalculationPrecision,
  type CalculationRoundingMode,
  calculateFinancialTotals,
  calculateGroupedTableTotals,
  calculateInvoiceTotals,
  calculateNumericAggregate,
  calculateTableTotals,
  calculateTaxDeductibleAmount,
} from './calculations';
export { type TemplateCategory, TemplateCategorySchema } from './categories';
export {
  type ConditionalEvaluationDiagnostic,
  type ConditionalEvaluationDiagnosticCode,
  type ConditionalEvaluationDiagnosticSeverity,
  type ConditionalRuleEvaluationResult,
  type ConditionalRulesEvaluationResult,
  type EvaluateConditionalRuleInput,
  type EvaluateConditionalRulesInput,
  evaluateConditionalRule,
  evaluateConditionalRules,
} from './conditions';
export {
  defaultVariableFormatters,
  type FormatVariableValueInput,
  formatVariableValue,
  type NormalizedVariableFormatterOptions,
  normalizeVariableFormatterOptions,
  type VariableFormatResult,
  type VariableFormatter,
  type VariableFormatterContext,
  type VariableFormatterMap,
  type VariableFormatterOptions,
  type VariableResolutionDiagnostic,
  type VariableResolutionDiagnosticCode,
  type VariableResolutionDiagnosticSeverity,
} from './formatters';
export {
  type AuditEvent,
  AuditEventSchema,
  type BatchRunV1,
  BatchRunV1Schema,
  type DocumentArtifact,
  DocumentArtifactSchema,
  type RenderError,
  RenderErrorSchema,
  RendererSchema,
  type RenderJobV1,
  RenderJobV1Schema,
  RenderModeSchema,
  type RenderRequest,
  RenderRequestSchema,
  type RenderResult,
  RenderResultSchema,
  type RenderWarning,
  RenderWarningSchema,
} from './rendering';
export {
  type CreateScopedRepeaterContextInput,
  createScopedRepeaterContext,
  type RepeaterResolutionDiagnostic,
  type RepeaterResolutionDiagnosticCode,
  type RepeaterResolutionDiagnosticSeverity,
  type ResolvedRepeaterItem,
  type ResolveRepeaterItemsInput,
  type ResolveRepeaterItemsResult,
  resolveRepeaterItems,
} from './repeaters';
export {
  type ResolvedTableCell,
  type ResolvedTableRow,
  type ResolveTableRowsInput,
  type ResolveTableRowsResult,
  resolveTableRows,
  type TableResolutionDiagnostic,
  type TableResolutionDiagnosticCode,
  type TableResolutionDiagnosticSeverity,
} from './tables';
export {
  type AssetReference,
  AssetReferenceSchema,
  AssetRoleSchema,
  CustomPageSizeSchema,
  type DocumentContent,
  type DocumentContentNode,
  DocumentContentNodeSchema,
  DocumentContentSchema,
  DocumentEngineSchema,
  type DocumentPageSettings,
  DocumentPageSettingsSchema,
  type DocumentTemplateV1,
  DocumentTemplateV1Schema,
  type DocumentTheme,
  DocumentThemeSchema,
  PageMarginsSchema,
  PageOrientationSchema,
  PageSizeSchema,
  PageUnitSchema,
} from './template';

export {
  createVariableResolver,
  getValueAtDataPath,
  type ResolvedVariableValue,
  type ResolveVariableValueInput,
  type ResolveVariableValuesInput,
  type ResolveVariableValuesResult,
  resolveVariableValue,
  resolveVariableValues,
  type VariableDataContext,
  type VariablePathLookupResult,
  type VariableResolutionRequest,
  type VariableResolutionRequestInput,
  type VariableResolutionStatus,
  type VariableResolver,
  type VariableResolverOptions,
} from './variable-resolution';

export {
  coreVariableDefinitions,
  coreVariableRegistry,
  createVariableRegistry,
  type FallbackBehavior,
  FallbackBehaviorSchema,
  type PrivacyClassification,
  PrivacyClassificationSchema,
  type RegistryVariableDefinition,
  type RegistryVariableDefinitionInput,
  RegistryVariableDefinitionSchema,
  type VariableDefinition,
  VariableDefinitionSchema,
  type VariableGroup,
  VariableGroupSchema,
  type VariableReference,
  VariableReferenceSchema,
  type VariableRegistry,
  VariableRegistryError,
  type VariableRegistryErrorCode,
  type VariableSampleData,
  type VariableValueType,
  VariableValueTypeSchema,
} from './variables';
